---
settings:
  commit:
    format: "<%- prefix %>: <%- subject %>"
    prefix: "chore"
    subject: "sync files from `<%- repository %>`"
  pull_request:
    reviewers:
      - "shmileee"
    labels:
      - "auto-sync"
    title: "chore: sync files from `<%- repository %>`"
    merge:
      mode: auto
      strategy: squash
      delete_branch: true

patterns:
  - files:
      - .markdownlintrc
      - .github/renovate.json
    template:
      organization:
        name: "DevOps Roast"
        name_normalized: "devops-roast"
        url: "https://devops-roast.com"
        contact_email: "contact@devops-roast.com"
    repositories:
      - devops-roast/containers
