---
name: sync-files

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  sync-files:
    uses: devops-roast/github-actions/.github/workflows/sync-files.yaml@main
    secrets: inherit
